### ISSUE TITLE
How to setup and run tests?

### ISSUE THREAD

**Issue by edgebyte-ai** [smok-serwis/snakehouse#8]
1. setup venv, activate venv.
2. in the snakehouse root folder, type "pip install ." to install snakehouse and cython
3. in the snakehouse\example folder, type "pip install .", it will enter endless loop, has to kill the root python3.9.exe
4. found some __init__.py was changed, has to reset: "git reset --hard"
5. in the snakehouse\example folder, type "python -m setup.py install", it builds and installs the example.
6. in the snakehouse\example folder, type "python -m unittest tests.test_test, it shows:
![image](https://user-images.githubusercontent.com/1857661/162696929-477a2250-5878-4dea-a66c-2be56d8951d1.png)

**Comment by piotrmaslanka** [comment]
I suggest you import these within the tests, so you should do:

```
class Unittest(TestCase):
   def test_sth(self):
      from example_module.test import times_two
```

I do now know how to fix this, but this is effected by the Python import machinery.
